# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611498e140623cc7231e967e1f48e53ea7f6e4e6cc0eb7d11cab7af61421f082cad847ee71d60a81a70e9660ea4e8205066b458b0a9139eda21fe1efd4bc77b0

test:
  secret_key_base: 2cbb46c734534a5735517c923ebd8e9fb2bf8eedb3f52bcec9b1955fd9bc070331486a70061499ca14d03e936dc23cc8c8e8f4737efe956e89ab9c7971d91e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
